CREATE DATABASE IF NOT EXISTS ecf_ccp2;
USE ecf_ccp2;
CREATE TABLE IF NOT EXISTS users (id INT AUTO_INCREMENT PRIMARY KEY NOT NULL, name VARCHAR(100) NOT NULL, email VARCHAR(300) NOT NULL, password VARCHAR(500) NOT NULL);
CREATE TABLE IF NOT EXISTS course (id INT AUTO_INCREMENT PRIMARY KEY NOT NULL, name VARCHAR(100) NOT NULL, content LONGTEXT NULL);
CREATE TABLE IF NOT EXISTS session (id INT AUTO_INCREMENT PRIMARY KEY NOT NULL, token VARCHAR(400) NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
INSERT INTO course (name, content) VALUES ('First course', 'This is a course');
CREATE USER 'app_user'@'%' IDENTIFIED BY 'AppUser123!';
GRANT SELECT, INSERT, UPDATE, DELETE ON ecf_ccp2.course TO app_user@'%';
FLUSH PRIVILEGES